### ISSUE TITLE
Server replied with status code 500: INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by tobycoder** [amcat/amcat#515] opened 2016-05-03 06:26 UTC
Hi,

I've got a little struggle in AmCAT. I hope you can help me with this.

When I try to run a query, AmCAT returns:

`Unknown error. Server replied with status code 500: INTERNAL SERVER ERROR`

Sometimes AmCAT runs my query, but that's only for a few minutes..

I tried:
- refresh with ctrl-f5/shift-f5
- restart browser
- log out and log in
- restart desktop
- other projects

But nothing helps. Can you help me with this?

Thanks in advance,

Floris

**Comment by martijnbastiaan** [comment] 2016-05-03 06:41
Could you attach a sample query you're running? Screenshot would be perfect.

Floris de Boer <notifications@github.com> schreef op 3 mei 2016 08:26:50 CEST:
>Hi,
>
>I've got a little struggle in AmCAT. I hope you can help me with this.
>
>When I try to run a query, AmCAT returns:
>
>`Unknown error. Server replied with status code 500: INTERNAL SERVER
>ERROR`
>
>Sometimes AmCAT runs my query, but that's only for a few minutes..
>
>I tried:
>- refresh with ctrl-f5/shift-f5
>- restart browser
>- log out and log in
>- restart desktop
>- other projects
>
>But nothing helps. Can you help me with this?
>
>Thanks in advance,
>
>Floris
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/amcat/amcat/issues/515

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tobycoder** [comment] 2016-05-03 07:15
![screenshot 16](https://cloud.githubusercontent.com/assets/16070468/14976841/76783722-110f-11e6-8886-69a961cd7802.png)

So this is what I get everytime when I'm running queries

**Comment by vanatteveldt** [comment] 2016-05-03 08:00
I think this is another occurrence of the issue with removed sets still appearing in the query selection because they are still 'favourite'.

Can you try the query with only a single set, e.g. https://amcat.nl/navigator/projects/2/query/?sets=27916#summary ? That works fine for me, but it goes wrong if I select all sets in project 2.

**Comment by tobycoder** [comment] 2016-05-03 08:39
One set works just perfect.. 
![screenshot 17](https://cloud.githubusercontent.com/assets/16070468/14978316/454d2cbe-111b-11e6-8094-782a3cfca57a.png)

**Comment by vanatteveldt** [comment] 2016-05-03 08:55
So I think indeed the problem is with a particular set in project 2. When you said "other projects", what did you mean? 

Solution for now: don't use all sets (which is nonsensical anyway, all newspapers should be in set 2). 

Closing the issue as it is a duplicate of #507

**Closed by vanatteveldt** 2016-05-03 08:55 UTC
