### ISSUE TITLE
deduplicate doesn't work

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#535] opened 2016-05-19 11:46 UTC
when deduplicating it states the duplicates are gone but in fact they are still in the set.
When deduplicating set 1257 in Eur.amcat.nl project 94 and skipping everything excpt the text it states to have deleted 635 duplicates. However the same amount of articles are found in the set. 
Underneath two examples. the different sections etc I took into account since I skipped sections etc (see above)
http://eur.amcat.nl/navigator/projects/94/articles/207071/
http://eur.amcat.nl/navigator/projects/94/articles/207032/

![image](https://cloud.githubusercontent.com/assets/6438205/15392507/c6c254b4-1dc7-11e6-9a5f-cfbafd7e3eb9.png)

**Comment by vanatteveldt** [comment] 2016-05-19 12:05
Not sure why the amount of articles doesn't change, but the text on these articles is not identical:

http://eur.amcat.nl/navigator/projects/94/articles/207071/ ends with 
```
The rest of Europe has a keener sense of boundaries - they've lived against the
limits of nature for longer
``` 

while http://eur.amcat.nl/navigator/projects/94/articles/207032/ has one more sentence

```
"The rest of Europe has a keener sense of boundaries - they've lived against the
limits of nature for longer."

· Naomi Klein will speak at Melbourne writers festival on 29 and 30
August and the Festival of Dangerous Ideas, Sydney on 5 September
```

**Comment by nruigrok** [comment] 2016-05-26 08:34
Well OK but the problem is that  AmCAT tells me that it deleted X articles from the articleset and they are still in the articleset....

**Comment by vanatteveldt** [comment] 2016-05-26 21:11
It seems that they are actually removed from the set, the problem is that the index is not refreshing properly:

```{python}
>>> s = ArticleSet.objects.get(pk=1257)
>>> s.refresh_index(full_refresh=True)
[..]
[2016-05-26 22:57:17,946 WARNING amcat.tools.amcates:410] Refreshing index, full_refresh=True,|solr_set_ids|=3921, |db_set_ids|=3764, |solr_ids|=3764 |to_add| = 3764, |to_add_set|=0, |to_remove_set|=157
[2016-05-26 22:57:17,946 INFO amcat.tools.amcates:412] Removing 157 articles
[2016-05-26 22:57:18,039 INFO amcat.tools.amcates:414] Adding 0 articles to set
[2016-05-26 22:57:18,039 INFO amcat.tools.amcates:416] Adding 3764 articles to index
[..]
[2016-05-26 22:57:32,675 INFO amcat.tools.amcates:418] Flushing
>>> 3764 + 157
3921
>>> s.articles.count()
3764
>>> s.get_count()
3921
```

**Comment by vanatteveldt** [comment] 2016-07-24 09:27
I'm closing this as eur.amcat.nl is running an older version and I'm assuming the problem is no longer urgent.

**Closed by vanatteveldt** 2016-07-24 09:27 UTC
