### ISSUE TITLE
Article permissions problematic for duplicates from another project (was: cannot open the articles)

### ISSUE THREAD

**Issue by EmLu96** [amcat/amcat#433] opened 2015-11-28 08:50 UTC
I have uploaded my own article set, however, there seems to be an overlap with the 2-dutch article set (or something like that). This prevents me from opening the articles all together, because if the articles overlap they're stored at the dutch newspaper set, and I am not authorized to look at those articles. 
Fucking frustrating :'(

**Comment by vanatteveldt** [comment] 2015-12-15 12:21
Hey EmLu,

I must have missed the (automatic) mail about this issue, sorry about that. Are you still waiting for a solution? 

I can confirm that this way of dealing with duplicates is problematic. Technically the problem is caused by:
1) view permission is determined by project membership
2) duplicates are added to the new set, but remain in the original project
3) so, duplicates from a restricted project cannot be seen

I think the only way out is to base article viewing permissions on set membership rather than project membership. This means that either (a) you can only save articles to a set if you have full reading rights on the source set(s) (so you cannot save results if you can't read articles, which can be annoying in some cases), or (b) that articlesets somehow get a "metareader" flag if saved without permissions, but that is also annoying since then you don't really know what you have. 

My current thinking is to go with (a), so 
- article viewing permission is based on the project that the articleset is in, not the project
- you can only save a set if you have full reading rights on all articles that you want to add to the set

(This also means that we can probably drop the "project" property of articles, since they are read-only anyway, so ownership doesn't really mean anything anymore if reading rights are no longer determined by it?)

@martijnbastiaan @nruigrok @carinajacobi @CJStuart do you all agree?

**Comment by vanatteveldt** [comment] 2016-01-16 15:24
Duplicate of #370

**Closed by vanatteveldt** 2016-01-16 15:24 UTC
Labels: bug, duplicate, enhancement
