### ISSUE TITLE
Error message when I click on "query" 

### ISSUE THREAD

**Issue by jitske-vkb** [amcat/amcat#753] opened 2019-10-18 13:35 UTC
When I click on "query" I see this error message: 

500 : An Error has occurred

ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fcce8421a10>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fcce8421a10>: Failed to establish a new connection: [Errno 111] Connection refused)

The server encountered an internal error or misconfiguration and was unable to complete your request.

------ Issue details -----
500 error on accessing:
https://amcat.nl/navigator/projects/2039/query/

**Comment by vanatteveldt** [comment] 2019-10-18 14:06
is it fixed now?

**Comment by jitske-vkb** [comment] 2019-10-18 15:53
Yes, many thanks!!

Op vr 18 okt. 2019 16:06 schreef Wouter van Atteveldt <
notifications@github.com>:

**Comment by jitske-vkb** [comment] 2019-10-20 14:00
Hi Wouter,

I am seeing the same error again, unfortunately.
Is there anyway you can fix this again?

Thank you and best wishes,
Jitske


Op vr 18 okt. 2019 om 16:06 schreef Wouter van Atteveldt <
notifications@github.com>:

**Comment by vanatteveldt** [comment] 2019-10-20 14:29
Yeah - the elasticsearch is killed, probably a memory issue. I've restarted it now, but if it happens again I guess we should look at the root cause...

**Closed by vanatteveldt** 2019-10-20 14:29 UTC
