### ISSUE TITLE
Upload problems: 'polling failed' and empty texts

### ISSUE THREAD

**Issue by Eschout** [amcat/amcat#584] opened 2017-04-12 11:33 UTC
I repeatedly get an error message when trying to upload (plain text) documents to my project in AmCAT. The error starts when importing a text, saying that 'polling failed'. I converted my .doc documents to .txt documents, and then the error disappeared. However, if I view the set and my uploaded text, the field is empty: al the metadata is there, but there is no text. Instead, is just says 'PK'. 
This problem happens for every text document I try to upload.

**Comment by vanatteveldt** [comment] 2017-04-12 12:38
Can you upload one of the files here?

**Comment by Eschout** [comment] 2017-04-12 12:47
[Artikel 01-02-2017.txt](https://github.com/amcat/amcat/files/916509/Artikel.01-02-2017.txt)
[Artikel 01-02-2017.docx](https://github.com/amcat/amcat/files/916511/Artikel.01-02-2017.docx)

Of course, here you find an example: it's one and the same document, only one is .docx and one is .txt.

**Comment by vanatteveldt** [comment] 2017-08-02 11:02
The .txt is not actually converted, it is simply the .docx file with a different extension, so it's no wonder that it doesn't yield a good outcome. 

I can confirm the .docx fails to upload, it even fails to start the uploader script (at least, nothing shows up in the log). 

Do you still need this? Otherwise, I'm closing the issue and making a new issue for amcat3.5, which is due to be released September 1st.

**Closed by vanatteveldt** 2017-08-02 11:02 UTC

**Comment by Eschout** [comment] 2017-08-02 14:34
I no longer need assistance; thanks!
