### ISSUE TITLE
"save article set" does not work on sets imported with "use in another project"

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#285] opened 2015-03-04 11:33 UTC
Background
"save article set" in continuously updated projects like 2-2 (newspapers) and 3-2221 (tv-tt888) renders a fuzzy mess of sets in projects 2 and 3.

Problem
However, this can not be prevented yet, since importing 2-2 or 3-2221 in anoher project, e.g. 704 "justifications of counter(terrorism)" with "use in another projecct", and thereafter "save as set" does not work:
- amcat will tell you first that it succeeded in saving the set, e.g. "nl_dagbladen dec14-feb15 n=23219" and will return the number of articles (n=23219).
- the set name is created indeed
- however, the set is empty (0 items)

**Comment by vanatteveldt** [comment] 2015-03-04 11:41
Can you try "refresh index" on the newly created set?

**Comment by Kleinnijenhuis** [comment] 2015-03-04 12:08
Gefikst! Dank voor de tip, issue afgesloten. Dank en hartelijke groet, Jan
________________________________
Van: Wouter van Atteveldt [notifications@github.com]
Verzonden: woensdag 4 maart 2015 12:41
Aan: amcat/amcat
CC: Kleinnijenhuis, J.
Onderwerp: Re: [amcat] "save article set" does not work on sets imported with "use in another project" (#285)


Can you try "refresh index" on the newly created set?

**Comment by vanatteveldt** [comment] 2015-04-02 18:24
Duplicate of #286, closing

**Closed by vanatteveldt** 2015-04-02 18:24 UTC
Labels: duplicate
