### ISSUE TITLE
CSV uploader throws cryptic errors

### ISSUE THREAD

**Issue by martijnbastiaan** [amcat/amcat#357] opened 2015-05-25 21:35 UTC
..even when uploading a CSV downloaded through amcat. This should never happen:

```python
[2015-05-25 23:32:52,062: ERROR/Worker-3] scraper._get_units failed
Traceback (most recent call last):
  File "/home/martijn/code/amcat/amcat/scripts/article_upload/controller.py", line 43, in run
    units = list(scraper._get_units())
  File "/home/martijn/code/amcat/amcat/scripts/article_upload/upload.py", line 185, in _get_units
    for entry in self.bound_form.get_entries():
  File "/home/martijn/code/amcat/amcat/scripts/article_upload/fileupload.py", line 182, in namedtuples_from_reader
    yield Row(*values)
TypeError: __new__() takes exactly 14 arguments (15 given)
[2015-05-25 23:32:52,088: ERROR/MainProcess] Task amcat.models.task.amcat_task[1b6f8ea3-794c-4a66-811f-9f02308666b3] raised unexpected: Exception('No articles were imported',)
Traceback (most recent call last):
  File "/home/martijn/code/amcat.env/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/martijn/code/amcat.env/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/martijn/code/amcat/amcat/models/task.py", line 46, in amcat_task
    return handler.run_task()
  File "/home/martijn/code/amcat/navigator/views/scriptview.py", line 92, in run_task
    result = script.run()
  File "/home/martijn/code/amcat/amcat/scripts/article_upload/csv_import.py", line 158, in run
    return super(CSV, self).run(*args, **kargs)
  File "/home/martijn/code/amcat/amcat/scripts/article_upload/upload.py", line 161, in run
    raise Exception("No articles were imported")
Exception: No articles were imported
```

**Comment by martijnbastiaan** [comment] 2015-05-25 21:36
This is also a good opportunity to critically review the current status of `fileupload.py` and its siblings.

**Comment by vanatteveldt** [comment] 2016-01-31 14:53
I'm calling this a dupe of https://github.com/amcat/amcat/issues/439

**Closed by vanatteveldt** 2016-01-31 14:53 UTC
Labels: bug
