### ISSUE TITLE
coding rules don’t seem to work

### ISSUE THREAD

**Issue by sebbelpiet** [amcat/amcat#660] opened 2018-01-15 14:42 UTC
Maybe this is only my misunderstanding of how to use them. But I can’t get a coding rule to work. 
I want to implement some sort of filter into the coding so that if a certain variable is coded in a certain way subsequent variables don’t have to be coded anymore. If I understand correctly that should be doable with the Amcat "Coding Rules" function. But it does not seem to be working properly.
For this codebook
https://amcat.nl/navigator/projects/1479/codingschemas/559/
for example I want to set a coding rule so that if variable “V36 Medienkritik” (id: 12696; fieldnr: 810) is coded “0 Kritik kommt nicht vor” (code-id: 86826) then the variable “V36a Medienkritik: Akteur 1” (id: 12695; fieldnr: 820) is not codable. 
So I added a coding rule with:
 
Label: Medienkritik Rule 1
If: (12696 == 86826)
Then for: V36a Medienkritik: Akteur 1
Apply: not codable
 
But still “V36a Medienkritik: Akteur 1” remains codable if “V36 Medienkritik” is coded as “0 Kritik kommt nicht vor”

**Comment by vanatteveldt** [comment] 2018-01-16 21:40
@CJStuart , can you have a look at this?

**Comment by CJStuart** [comment] 2018-02-15 16:28
Coding rules are partially fixed now. 

After fields have been changed, the rules are applied, and if they are invalid, 'finish and continue' will result in the coding being marked 'unfinished'. 
There are still some more issues, though:

Todo:

- [ ] Invalid fields must be marked red. 
- [ ] Validation must always be done when submitted. Currently, validation is only done after a change, and if fields are left unchanged, and 'finish & continue' will be accepted, even if invalid.
- [ ] The annotator shouldn't jump to the next article if the form is invalid.

**Comment by vanatteveldt** [comment] 2018-02-16 07:47
Cool!

When do you think these remaining issues will be solved?

**Comment by CJStuart** [comment] 2018-02-16 15:05
I resolved most of the remaining issues. However, I'm not sure about the intended behavior of the  'display red' option, and it currently does nothing.

**Comment by CJStuart** [comment] 2018-04-08 12:50
I believe this is behaving as intended now.

**Closed by CJStuart** 2018-04-08 12:50 UTC
