### ISSUE TITLE
AUTNES-Amcat: Query-function bugged?

### ISSUE THREAD

**Issue by andreasf22** [amcat/amcat#744] opened 2019-05-17 07:47 UTC
I am currently trying to use the Query-function in the AUTNES-amcat-version (http://autnes.amcat.nl/projects/3/articlesets/). I tried lots of different querys, including saved ones, but everytime I start the query, amcat freezes when searching for results (see screenshots attached). If I use a new query, the operation stops at "Waiting for task to start", when using an old saved query, it stops halfway at "Loading script."

Used querys were for example:
listepilz# "liste pilz" "pilz grün*"~5 "pilz spö"~5 "pilz övp"~5 "pilz fpö"~5 "pilz neos"~5 "pilz zadic"~5 "pilz holzinger"~5 "pilz kolba"~5 "pilz zinggl"~5 "pilz roscher"~5 "pilz chelucci"~5 "pilz nasswetter"~5 "pilz cox"~5 "pilz werthner"~5 "pilz bißmann"~5 "pilz rossmann"~5 "pilz schroeder"~5 "liste peter pilz"~10

10707# ( kurzarbeit* )
 
![Screenshot_New_Query_Bug](https://user-images.githubusercontent.com/50229588/57911051-07e6e000-7887-11e9-8f02-bbcdeef4c0eb.png)
![Screenshot_Saved_Query_Bug](https://user-images.githubusercontent.com/50229588/57911066-09b0a380-7887-11e9-9ec4-03cc5f9dd0db.png)

I have tried the classic go-to-solutions (refreshing browser, use different browsers (Firefox, Chrome, Edge, Explorer), restart the system, use different querys/different datasets). As none of that has work, I ran out of ideas to "fix" the problem myself. I am currently querying the article sets via R, each time creating a new article-set to check the result - that works, but it's not really a "fancy" way of operating.

Best regards, Andreas

**Comment by vanatteveldt** [comment] 2019-05-17 09:19
Hey Andreas,

I can confirm the problem. It's caused by a javascript error, probably a recent(ish) update. Let me see if I can find it!

- Wouter

**Comment by vanatteveldt** [comment] 2019-05-17 10:02
Problem was that a javascript change didn't get updated with the last update. 

Should be fixed now!

**Closed by vanatteveldt** 2019-05-17 10:02 UTC
