### ISSUE TITLE
factivia upload problems

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#582] opened 2017-04-11 09:39 UTC
From an email report:

I am part of a research group carrying out a framing analysis on newspaper articles during the official EU referendum campaign (for a course with Dr. Brandon Zicha) and we have been advised to use AmCat. We have tried uploading articles, downloaded from factiva and reverted to txt files, but it does not work. We tried uploading it through “Factivia”, in pdf form and in plain text and we also tried with documents holding less articles (around 17 articles instead of around 100). I was wondering whether there was something we could do to fix this. Thank you for your time.

**Comment by vanatteveldt** [comment] 2017-04-11 09:41
Hey Brandon / Anneclaire,

Our internal test files for factivia work without problem.
Could you post the factivia file that causes problems?

If you create a github account you can post comments/files here. 

-- Wouter

**Comment by AnneclaireKniese** [comment] 2017-04-11 11:08
Thank you! Okay so, we now have UK lexis nexis files and factiva files all in plain text.

this is one of our lexis nexis files:   
[WHAT_BREXIT_MEANS_TO_EU_IRISH_EYE_UP_VITAL_.TXT](https://github.com/amcat/amcat/files/912934/WHAT_BREXIT_MEANS_TO_EU_IRISH_EYE_UP_VITAL_.TXT) 
this is one of our factiva files: 
[Factiva plain text try 1000000.txt](https://github.com/amcat/amcat/files/912935/Factiva.plain.text.try.1000000.txt) 

Both don't work. For comparison, this file downloaded from the Dutch Lexis Nexis does work (although the whole article is missing): 
[Dutch_Language_News_-_Full_Text2017-04-10_14-01.TXT](https://github.com/amcat/amcat/files/912940/Dutch_Language_News_-_Full_Text2017-04-10_14-01.TXT)

**Comment by CJStuart** [comment] 2017-04-12 13:32
Hi Anneclaire, 

Do you happen to have access to Factivia HTML files? Those should work using the Factivia uploader. Currently we do  not have a parser that can handle Factivia plain text files.

Alternatively, a workaround for the LexisNexis parse failure would be to prepend the following line to the text files that contain only 1 article: 
```
1 OF 1 DOCUMENTS
```
This is the text that our parser uses to find the beginning of an article. If it is missing, it will not be able to find the articles. 
I think it might be possible to let AmCAT figure this out on its own in the future, I opened a new issue addressing this: #586

**Comment by AnneclaireKniese** [comment] 2017-04-12 15:13
Hi Christian, 

Thank you for your reply. How could I get access to Factiva HTML files? I saved one the factiva plain text files as an HTML file but that did not work either (I can't upload it to here either because HTML is not supported). Up until now, the only information I could find about Factiva and HTML files had to do with the Factiva developers kit. 

As for Lexis Nexis, we need to upload a lot of articles so we could avoid having to add "1 of 1 DOCUMENTS" before every article that would be preferable.

**Comment by AnneclaireKniese** [comment] 2017-04-12 18:47
![screen shot 2017-04-12 at 20 41 51](https://cloud.githubusercontent.com/assets/27280797/24974002/20da3312-1fc1-11e7-8e1e-2ed44dc21afc.png)
![screen shot 2017-04-12 at 20 42 03](https://cloud.githubusercontent.com/assets/27280797/24974006/26718956-1fc1-11e7-9796-b710e6c86dd3.png)
 This is what my HTML (webarchive to HTML) file looks like.

**Comment by CJStuart** [comment] 2017-04-12 21:30
I just pushed an update to AmCAT that allows the parser to parse LexisNexis files without the 'X OF Y DOCUMENTS' line. If you're using our server at https://amcat.nl, then it should be working now.

**Comment by AnneclaireKniese** [comment] 2017-04-13 09:22
Hi Christian, thank you for the update. This works in the case of one article per file so we would still have to add the 1 of 1 DOCUMENTS line before each article. If we can avoid that by making the Factiva files work that would be great, otherwise, too bad. 

Have you been able to identify differences between the Factiva HTML file i posted and your internal Factiva files?

**Comment by CJStuart** [comment] 2017-04-13 10:01
Those screenshots look exactly the same as our files. Could you tell me what happens if you try to upload those HTML files with the Factiva parser in AmCAT?

**Comment by AnneclaireKniese** [comment] 2017-04-13 10:16
![screen shot 2017-04-13 at 12 15 02](https://cloud.githubusercontent.com/assets/27280797/25000785/e6720880-2042-11e7-9b40-f2bb7f329c6a.png)
This is what I get.

**Comment by CJStuart** [comment] 2017-04-13 11:21
Apparently the problem was that the Factiva parser couldn't cope with English articles. I think I fixed the problem now. Please give it another try, and let me know if you run into more problems.

**Comment by AnneclaireKniese** [comment] 2017-04-13 11:40
Yes! It works, thank you so much.

**Comment by AnneclaireKniese** [comment] 2017-04-13 11:58
![screen shot 2017-04-13 at 13 51 33](https://cloud.githubusercontent.com/assets/27280797/25003756/41b98e58-2051-11e7-84d2-148ac3575a94.png)
One last question, is there a way that AmCat could recognise the "Features" as well?

**Comment by CJStuart** [comment] 2017-04-13 14:38
It shouldn't be too difficult, but I'm not sure what you want AmCAT to do with it. Should it be part of the headline?

**Comment by AnneclaireKniese** [comment] 2017-04-13 15:02
It could be part of the headline, yes. Or it could be recognised as "article type". It doesn't really matter but it is one of our variables, so it would be great if it could show up somewhere in amcat. Thank you!

**Comment by CJStuart** [comment] 2017-04-13 15:45
The current version that AmCAT is running does not support a lot of fields. In the future we will support custom fields. For now I could have it place the field into the 'section' field, which is currently not used by the Factiva parser. I'll can look into that tomorrow.

@vanatteveldt What's your opinion on this?

**Comment by AnneclaireKniese** [comment] 2017-04-13 16:54
If including it in the headline is easier that is more than fine too!

**Comment by AnneclaireKniese** [comment] 2017-04-15 17:18
The section field works now! However, there is one thing that I noticed and that is that the Date does not get processed. Right now the date it displays is the date of uploading the articles to AmCat not the date displayed here: 
![screen shot 2017-04-15 at 19 16 58](https://cloud.githubusercontent.com/assets/27280797/25065424/249be77e-2210-11e7-8571-7289acf3f6a6.png)
Sorry for bothering you again. Is this easily fixable?

**Comment by CJStuart** [comment] 2017-04-15 17:29
I'm having trouble reproducing the behaviour. I did notice, however, that the article coincidentally was written today, so the upload date and the publication date would be the same. Are you sure that the date is incorrect?

**Comment by AnneclaireKniese** [comment] 2017-04-15 17:36
Oh, I am so sorry! I completely forgot that I randomly chose an article from Factiva without specifying the date, so yes these are probably articles that were published today.

**Comment by CJStuart** [comment] 2017-04-26 12:33
I'm closing this issue. Feel free to reopen it if you run into more problems.

**Closed by CJStuart** 2017-04-26 12:33 UTC
Labels: bug
