### ISSUE TITLE
unexpected save amcat 

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#767] opened 2021-09-08 08:48 UTC
Thanks for helping us improve AmCAT by reporting an issue!
If you report a bug with AmCAT, please provide the following details if applicable:

1) What are you trying to do. 
Query > actions > save as new set
If applicable, please include:
 - URL of the page: https://vu.amcat.nl/projects/33/query/?sets=1972#summary
 - text of your query (please copy/paste, don't include a screenshot): Just as one example: 
 (groenlinks OR vvd OR forum OR baudet OR fvd OR rutte OR klaver) AND (klimaat* OR stikstof* OR milieu* OR (natuur* NOT  natuurlijk*))
 - any other settings or steps needed for us to reproduce the problem:
selection on media, e.g. NOS journaal 20.00
2) What is the result. If applicable, please include:
 - no writing permission????
 - the text of the error message or traceback, if given:
 code 403, no writing permission
 
![image](https://user-images.githubusercontent.com/6690321/132477479-c5641ddc-921c-4e32-aed6-7131a5e690c1.png)

**Comment by vanatteveldt** [comment] 2021-09-08 09:31
The message tells you it's forbidden because you don't have write access to this project. This is the intended behaviour so closing the issue as it's not a bug.

**Closed by vanatteveldt** 2021-09-08 09:31 UTC
