### ISSUE TITLE
Clicking on graph per day does not work (timezone issue)

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#142] opened 2014-05-14 12:20 UTC
Creating a graph and clickin on a point gives a javascript error and nothing happens.

i.e. http://amcat.vu.nl/navigator/projects/449/query/?articlesets=10224 -> graph -> submit 

Chrome: 

```
click 907200000000 10065 - The Toronto Star 2 76592e2d43cc.js:110
Uncaught TypeError: undefined is not a function 
```

FF:
```
Empty string passed to getElementById(). 09b9bf45def3.js:1
"click" 907192800000 "10065 - The Toronto Star" 2
```

Source line seems to be:
```
amcat.selection.aggregation.click=function(x,y,count){console.log('click',x,y,count);var form_values=amcat.selection.getFormDict();var added_form_values={};var title=count+' '+amcat.selection.aggregation.aggregationType+' ';if(amcat.selection.aggregation.xAxis=="date"){var date_clicked=start_date=end_date=new Date(x.split(" ")[0]);var datetype=amcat.selection.aggregation.dateType;if(datetype=="day"){added_form_values["datetype"]="on";var on_date=start_date.getFullYear()+"-"+(start_date.getMonth()+1)+"-"+start_date.getDate();added_form_values["on_date"]=amcat.selection.aggregation.reverseDateOrder(on_date);title+=' on '+added_form_values['on_date'];}else if(!isNaN(x)){$.each(amcat.selection.aggregation.datesDict,function(i,dt){var _start=new Date(dt[0]);if(_start.getTime()==date_clicked.getTime()){start_date=dt[0];end_date=dt[1];}});}else{start_date=amcat.selection.aggregation.datesDict[x][0];end_date=amcat.selection.aggregation.datesDict[x][1];}

```

**Comment by CJStuart** [comment] 2016-01-11 18:14
Appears to be fixed in 3.4 (could not reproduce).

**Closed by CJStuart** 2016-01-11 18:14 UTC
Labels: bug
