### ISSUE TITLE
'Undefined error' for clustermap and associations graphs

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#465] opened 2016-02-12 13:15 UTC
I get an undefined error for both clustermap and association graphs

Clustermap:
![clustermapgraph](https://cloud.githubusercontent.com/assets/6417728/13007638/f5d95bd0-d191-11e5-876c-d4699a6ccf27.png)

Associations:
![networkgraph](https://cloud.githubusercontent.com/assets/6417728/13007647/05337408-d192-11e5-9383-f0112b28ebc7.png)

Creating an associations table instead of graph (from the same data and search strings) does not lead to an error. The search string input looks like this (I also tried different search strings, but same problem):

![input](https://cloud.githubusercontent.com/assets/6417728/13007791/e7b5bdc2-d192-11e5-9df7-c75ef77b202d.png)

**Comment by CJStuart** [comment] 2016-02-12 14:45
Association graph errors have been fixed in 03b89b3, but i'm having trouble reproducing the clustermap error on my local machine.

**Comment by CJStuart** [comment] 2016-02-12 14:54
Appears to have been caused by a missing java installation.

**Closed by CJStuart** 2016-02-12 14:54 UTC
